# -*- coding: utf-8 -*-
"""Scatterplot with Data Visualization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yuzJTGgKQHtvQ6qrpKfjpUCSSIpHCE3G
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

data=pd.read_csv('new.csv')

x=data.x.to_numpy()
y=data.y.to_numpy()

plt.scatter(x,y)

x=x/500.0
y=y/500.0

m,c=np.random.random(),np.random.random()
def learn(x,y,m,c,epoch):
  for i in range(epoch):
    error=y-(m*x+c)
    x_error=(y-(m*x+c))*x
    error=np.sum(error)/len(x)
    x_error=np.sum(x_error)/len(x)
    learning_rate=0.01
    delta_m=learning_rate*x_error
    delta_c=learning_rate*error
    m+=delta_m
    c+=delta_c
  return(m,c)
m,c=learn(x,y,m,c,20000)
x1=[0,1]
y1=[0*m+c,1*m+c]
plt.scatter(x,y)
plt.plot(x1,y1)